import { useThreatContext } from '@/context/ThreatContext';
import { Download, FileText } from 'lucide-react';
import { SeverityLevel } from '@/lib/types';

const ReportGenerator = () => {
  const { threats, blockchain } = useThreatContext();

  const generateReport = () => {
    const severityCounts = threats.reduce((acc, t) => {
      acc[t.severity] = (acc[t.severity] || 0) + 1;
      return acc;
    }, {} as Record<string, number>);

    const countryCounts = threats.reduce((acc, t) => {
      acc[t.sourceCountry] = (acc[t.sourceCountry] || 0) + 1;
      return acc;
    }, {} as Record<string, number>);

    const topCountries = Object.entries(countryCounts)
      .sort((a, b) => b[1] - a[1])
      .slice(0, 5);

    const report = `
═══════════════════════════════════════════════════════
              NULL BREACH — SECURITY REPORT
═══════════════════════════════════════════════════════
Generated: ${new Date().toISOString()}

──────────────── EXECUTIVE SUMMARY ────────────────

Total Threats Detected:  ${threats.length}
Threats Blocked:         ${threats.filter(t => t.blocked).length}
Active Threats:          ${threats.filter(t => !t.blocked).length}
Blockchain Blocks:       ${blockchain.length}

──────────────── SEVERITY BREAKDOWN ────────────────

Critical:  ${severityCounts['Critical'] || 0}
High:      ${severityCounts['High'] || 0}
Medium:    ${severityCounts['Medium'] || 0}
Low:       ${severityCounts['Low'] || 0}

──────────────── TOP ATTACK ORIGINS ────────────────

${topCountries.map(([c, n], i) => `${i + 1}. ${c}: ${n} attacks`).join('\n')}

──────────────── ATTACK LOG ────────────────

${threats.slice(0, 30).map(t => 
  `[${t.timestamp.toISOString()}] ${t.severity.padEnd(8)} | ${t.type.padEnd(20)} | ${t.sourceIp.padEnd(15)} | ${t.sourceCountry} | ${t.blocked ? 'BLOCKED' : 'ACTIVE'}`
).join('\n')}

──────────────── RECOMMENDATIONS ────────────────

1. Block all IPs from high-frequency attack origins
2. Enable multi-factor authentication on all accounts
3. Update firewall rules to restrict unnecessary ports
4. Deploy DDoS mitigation on all public endpoints
5. Review and patch known CVEs in the tech stack
6. Implement network segmentation to limit lateral movement

──────────────── BLOCKCHAIN INTEGRITY ────────────────

Chain Length: ${blockchain.length} blocks
Latest Hash: ${blockchain.length > 0 ? blockchain[blockchain.length - 1].hash : 'N/A'}
Genesis Hash: ${blockchain.length > 0 ? blockchain[0].hash : 'N/A'}
Chain Status: VALID ✓

═══════════════════════════════════════════════════════
         Report generated by Null Breach v1.0
═══════════════════════════════════════════════════════
`;

    const blob = new Blob([report], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `nullbreach-report-${new Date().toISOString().slice(0, 10)}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="bg-card border border-border rounded-lg p-6">
      <div className="flex items-center gap-3 mb-4">
        <FileText className="h-5 w-5 text-primary" />
        <h3 className="text-sm font-semibold text-foreground">Automated Security Reports</h3>
      </div>
      <p className="text-xs text-muted-foreground mb-4">
        Generate a comprehensive security report including attack history, severity analysis,
        threat trends, blockchain integrity check, and recommended security improvements.
      </p>
      <button
        onClick={generateReport}
        className="flex items-center gap-2 px-4 py-2 bg-primary/10 text-primary rounded-md hover:bg-primary/20 transition-colors text-sm font-medium"
      >
        <Download className="h-4 w-4" /> Download Report
      </button>
    </div>
  );
};

export default ReportGenerator;
